### PR TITLE
#166978192 Fix login and sign up using social auth

### PR DESCRIPTION
**Pull request by aaronsekisambu**
### What does this PR do?
Fix the login and sign up using social auth

### Description of Task to be completed?
- User should be able to log in via Facebook
- User should be able to log in via google
### How should this be manually tested?
- Clone the repository locally with `git clone https://github.com/andela/ah-kgl-avengers-frontend.git` command.
- Check out to this branch by running `git checkout ch-Fix-login-and-sign-up-using-social-auth-166978192 `.
- Install dependencies by running `npm install`.
- Update the .env file according to the .env.sample file
- Start the server with `npm start` and put this url `http://localhost:8000/` in the address bar.
- Login or Sign up with either Facebook or Google
### Any background context you want to provide?
This ticket also fixes the responsiveness of the social login buttons.
### What are the relevant pivotal tracker stories?
[#166978192 Fix the login and sign up using social auth](https://www.pivotaltracker.com/story/show/166978192)
### Screenshots (if appropriate)
image

### Questions:
N/A

### CODE REVIEW

**Comment by avpaul** [comment]
`git checkout ch-Fix-login-and-sign-up-using-social-auth-166978192` @aaronsekisambu  According to the Andela naming conventions the branch name should not have more than 3 words ex: `ch-fix-social-login-166978192`

**Review by niyobobo — CHANGES_REQUESTED** [review]
Good work @aaronsekisambu for your initiative but you have to work on your test as communicated by the TTL.

**Review by avpaul — CHANGES_REQUESTED** [review]
@aaronsekisambu  When would you please add the whole user object in local storage so that we can have it identical to the local login. Refer to this code [here](https://github.com/andela/ah-kgl-avengers-frontend/pull/28/files#diff-ad853751318eab0b54f29ed424e084fbR48)
```javascript
localStorage.setItem('user', JSON.stringify(user));
```

**Comment by aaronsekisambu** [comment]
@avpaul and @niyobobo Resolved.

**Review by avpaul — APPROVED** [review]

**Review by niyobobo — APPROVED** [review]
Thank you for good work and make our application looks clean.

**Review by ezkemboi — APPROVED** [review]
Good work.

**Pull request merged**
